const messages = [
    "Don't forget to put milk in your coffee, it makes it quite divine",
    "SAVE THE SLUGS!",
    "Today you will meet a molerat named sandy, and if your lucky, she might buy you a muffin top",
    "Don't forget to water your plants, they need love too",
    "You must take a break and go outside, the sun is shining and the birds are singing",
    "Don't forget to call your mom, she misses you",
    "Pain is just a mindset",
    "Don't forget to take a shower, you don't want to smell like a sratch-and-sniff card",
    "Careful, there might be something unplesant under your bed...",
    "EAT YOUR BROCCILI!",
    "Floss every night, your dentist is watching",
    "Always be careful when wearing a tie, it is a perfect noose",
    "It's not a bug, it's a beautiful arachnid",
    "It's not polite to stare",
    "Foamed milk is perfect for slurping",
    "Remember, you are a beautiful and unique snowflake... just like everyone else",
    "Don't yell so much, your neighbors might call the cops",
    "Gossip will get you nowhere and it might ruin your reputation, but it sure is fun",
    "Water is a nessary part of your diet, but it tastes better when you put it in your coffee",
    "Hug your dad today, he might need it",
    "Fortunes aren't predictions, they are a product of someone very closly watching",
    "The world is a crazy place, so be sure to tie your shoe laces so you don't trip",
    "Freedom is worth dieing for, but when everyone dies, no ones free",
    "STARING CONTEST! GO! O_O",
];